{
  "openapi": "3.0.0",
  "info": {
    "title": "Rick and Morty",
    "description": "API crud Rick and Morty",
    "termsOfService": "",
    "contact": {
      "email": "nascilino@gmail.com.br"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "API de teste"
    },
    
    {
      "url": "https://backrickandmortyblue2022.onrender.com/api-docs",
      "description": "API de teste"
    },

    
    {
      "url": "",
      "description": ""
    }
  ],
  "paths": {
    "/characters": {
      "get": {
        "summary": "Lista de todos os personagens",
        "description": "Rota responsável por listar todas os personagens de Rick and MOrty",
        "tags": ["Personagem"],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "404": {
            "description": "Not Found"
          },

          "401": { "description": "Unauthorized" },

          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": ""
                  },
                  "examples": {
                    "Personagens": {
                      "value": {
                        "name": "Morty Smith",
                        "url": "https://rickandmortyapi.com/api/location/3"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/characters/find/{id}": {
      "get": {
        "summary": "Busca um personagem pelo ID",
        "description": "Rota responsável por buscar uma personagem de Rick and Morty pelo ID",
        "tags": ["Personagem"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do personagem",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "401": { "description": "Unauthorized" },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "examples": {
                  "Personagens": {
                    "value": {
                      "_id": "627994627532fcd299bf08f2"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/characters/searchCharacters": {
      "get": {
        "summary": "Busca um personagem pelo nome",
        "description": "Rota responsável por buscar uma personagem de Rick and Morty pelo nome",
        "tags": ["Personagem"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "message",
            "in": "query",
            "description": "Nome do personagem",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },

          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": ""
                },

                "examples": {
                  "Personagens": {
                    "value": {
                      "name": "Morty"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/characters/create": {
      "post": {
        "summary": "Cadastrar um personagem",
        "description": "Rota responsável por cadastrar um personagem de Rick and Morty",
        "tags": ["Personagem"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": ""
              },
              "examples": {
                "Personagem": {
                  "value": {
                    "name": "Morty Smith",
                    "url": "https://rickandmortyapi.com/api/location/3"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "401": { "description": "Unauthorized" },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "examples": {
                  "Personagem": {
                    "value": {
                      "name": "Morty Smith",
                      "url": "https://rickandmortyapi.com/api/location/3",
                      "__v": 0
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/characters/update/{id}": {
      "put": {
        "summary": "Editar um personagem do Rick and Morty pelo ID",
        "description": "Rota responsável por editar um personagem do Rick and Morty pelo ID",
        "tags": ["Personagem"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do personagem para a busca",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": ""
              },
              "examples": {
                "Personagens": {
                  "value": {
                    "name": "Morty Smith editado",
                    "url": "https://rickandmortyapi.com/api/location/3"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "404": {
            "description": "Not Found"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": { "description": "Unauthorized" },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "examples": {
                  "Personagem": {
                    "value": {
                      "name": "Morty Smith",
                      "url": "https://rickandmortyapi.com/api/location/3",
                      "__v": 1
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/characters/delete/{id}": {
      "delete": {
        "summary": "Apagar um personagem de Rick and Morty pelo ID",
        "description": "Rota responsável por apagar um personagem de Rick and Morty pelo ID",
        "tags": ["Personagem"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do personagem para deleção",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "401": { "description": "Unauthorized" },
          "200": {
            "description": "OK"
          }
        }
      }
    },

    "/users": {
      "get": {
        "summary": "Lista de todos os usuários",
        "description": "Rota responsável por listar todas os Usuários",
        "tags": ["Users"],
        "responses": {
          "404": {
            "description": "Not Found"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": ""
                  }
                }
              }
            }
          }
        }
      }
    },

    "/users/create": {
      "post": {
        "summary": "Cadastrar um novo usuário",
        "description": "Rota responsável por cadastrar um novo usuário",
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": ""
              },
              "examples": {
                "Personagem": {
                  "value": {
                    "name": "Leonardo 4",
                    "username": "ruiz4856",
                    "email": "leonardo@89blue.com",
                    "password": "BLUE2019",
                    "avatar": "teste avatar"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": ""
                },
                "examples": {
                  "Personagem": {
                    "value": {
                      "_id": "627994627532fcd299bf08f2",
                      "name": "Leonardo 4",
                      "username": "ruiz4856",
                      "email": "leonardo@89blue.com",
                      "avatar": "teste avatar",
                      "__v": 0
                    }
                  }
                }
              }
            }
          }
        }
      }
    },

    "/auth/login": {
      "post": {
        "summary": "Fazer Login",
        "description": "Rota responsável por fazer Login",
        "tags": ["Autentificação"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": ""
              },
              "examples": {
                "User": {
                  "value": {
                    "email": "leonardo@89blue.com",
                    "password": "BLUE2019"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "200": {
            "description": "OK"
          },
          "content": {
            "application/json": {
              "examples": {
                "Personagem": {
                  "value": {
                    "token": "dsyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjOyNzlhNjhmMGRkMjVlZWE1OWRkZGEyOCIsImlhdCI6MTY1MjE0MDA3MSwiZXhwIjoxNjUyMjI2NDcxfQ.7p6w6TxIBd-pRrTC_PUR9D4QS2ZM25iX6B_QQARMnQU"
                  }
                }
              }
            }
          }
        }
      }
    }
  },

  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }, "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "avatar": {
            "type": "string"
          }
        }
      }


    }
  }
}
